[[trials]]
== Trial: Binaries to be Tested

A trial is a set of pre-built binaries to be tested. They are typically built
by jenkins using the build scripts found in osmo-gsm-tester's source in the
'contrib/' dir, see <<install_add_jenkins_slave>>.

A trial comes in the form of a directory containing a number of '*.tgz' tar
archives as well as a 'checksums.md5' file to verify the tar archives'
integrity.

When the osmo-gsm-tester is invoked to run on such a trial directory, it will
create a sub directory named 'inst' and unpack the tar archives into it.

For each test run on this trial, a new subdirectory in the trial dir is
created, named in the form of 'run.<timestamp>'. A symbolic link 'last-run'
will point at the most recently created run dir. This run dir will accumulate:

* the rendered configuration files used to run the binaries
* stdout and stderr outputs of the binaries
* pcap files for processes doing relevant network communication
* a test log
* jenkins parsable XML (Junit) reports

The script in 'contrib/jenkins-run.sh' takes care of related tasks such as

* creating the dir structure,
* generating md5 sums for the various tar.gz containing software builds to be tested,
* cleaning up after the build,
* saving extra logs such as journalctl output from ofonod,
* generating a final .tar.gz file with all the logs and reports.
