== Configuring OsmoSIPConnector

The configuration of OsmoSIPConnector consists mainly of two parts:
configuring the MNCC interface towards the MSC and configuring the SIP
interface towards the PBX.

=== Configuring MNCC

Configuring the MNCC interface is very simple. It has to be pointed to
the same path that OsmoMSC is also using. This means that OsmoMSC and
OsmoSIPConnector need to be running on the same machine or have a shared
directory that supports UNIX domain sockets.

The example config below assumes that OsmoMSC was started with the command
line `osmo-msc -M /tmp/msc_mncc`.

.Example: MNCC configuration
----
OsmoMGW(config)# mncc
OsmoMGW(config-mncc)# socket-path /tmp/msc_mncc
----

=== Configuring SIP

This section covers the SIP configuration. Source and destination IP and port
can be set for the connection to the PBX.

.Example: SIP configuration
----
OsmoMGW(config)# sip 
OsmoMGW(config-sip)# local 10.0.0.1 5060 <1>
OsmoMGW(config-sip)# remote 10.0.0.2 5060 <2>
----
<1> The local IP/port to use
<2> The remote SIP IP/port that the PBX uses

There is also an option to use the IMSI as calling (source) address for
MO- and as called (destination) address for MT-calls.

.Example: Use IMSI instead of MSISDN
----
OsmoMGW(config)# app
OsmoMGW(config-app)# use-imsi <1>
----
<1> Use the IMSI for MO calling and MT called address

Since OsmoSIPConnector is just a shim between OsmoMSC and a proper SIP server
this is the extent of the configuration. Setting up a dialplan and other
SIP-related configuration should be done in the actual SIP server.
