
[[bibliography]]
== Appendix A. Bibliography / References

[bibliography]
- [[[osmobts-abis-spec]]] Neels Hofmeyr & Harald Welte. OsmoBTS Abis
  Protocol Specification.
  http://ftp.osmocom.org/docs/latest/osmobts-abis.pdf
- [[[userman-osmobts]]] Osmocom Project: OsmoBTS User Manual.
  http://ftp.osmocom.org/docs/latest/osmobts-usermanual.pdf
- [[[vty-ref-osmobts]]] Osmocom Project: OsmoBTS VTY Reference Manual.
  http://ftp.osmocom.org/docs/latest/osmobts-vty-reference.pdf
- [[[userman-osmobsc]]] Osmocom Project: OsmoBSC User Manual.
  http://ftp.osmocom.org/docs/latest/osmobsc-usermanual.pdf
- [[[vty-ref-osmobsc]]] Osmocom Project: OsmoBSC VTY Reference Manual.
  http://ftp.osmocom.org/docs/latest/osmobsc-vty-reference.pdf
- [[[userman-osmomsc]]] Osmocom Project: OsmoMSC User Manual.
  http://ftp.osmocom.org/docs/latest/osmomsc-usermanual.pdf
- [[[vty-ref-osmomsc]]] Osmocom Project: OsmoMSC VTY Reference Manual.
  http://ftp.osmocom.org/docs/latest/osmomsc-vty-reference.pdf
- [[[userman-osmohlr]]] Osmocom Project: OsmoHLR User Manual.
  http://ftp.osmocom.org/docs/latest/osmohlr-usermanual.pdf
- [[[vty-ref-osmohlr]]] Osmocom Project: OsmoHLR VTY Reference Manual.
  http://ftp.osmocom.org/docs/latest/osmohlr-vty-reference.pdf
- [[[userman-osmopcu]]] Osmocom Project: OsmoPCU User Manual.
  http://ftp.osmocom.org/docs/latest/osmopcu-usermanual.pdf
- [[[vty-ref-osmopcu]]] Osmocom Project: OsmoPCU VTY Reference Manual.
  http://ftp.osmocom.org/docs/latest/osmopcu-vty-reference.pdf
- [[[userman-osmonitb]]] Osmocom Project: OsmoNITB User Manual.
  http://ftp.osmocom.org/docs/latest/osmonitb-usermanual.pdf
- [[[vty-ref-osmonitb]]] Osmocom Project: OsmoNITB VTY Reference Manual.
  http://ftp.osmocom.org/docs/latest/osmonitb-vty-reference.pdf
- [[[userman-osmosgsn]]] Osmocom Project: OsmoSGSN User Manual.
  http://ftp.osmocom.org/docs/latest/osmosgsn-usermanual.pdf
- [[[vty-ref-osmosgsn]]] Osmocom Project: OsmoSGSN VTY Reference Manual.
  http://ftp.osmocom.org/docs/latest/osmonitb-vty-reference.pdf
- [[[userman-osmoggsn]]] Osmocom Project: OpenGGSN User Manual.
  http://ftp.osmocom.org/docs/latest/osmoggsn-usermanual.pdf
- [[[vty-ref-osmoggsn]]] Osmocom Project: OsmoGGSN VTY Reference Manual.
  http://ftp.osmocom.org/docs/latest/osmoggsn-vty-reference.pdf
- [[[3gpp-ts-23-048]]] 3GPP TS 23.048: Security mechanisms for the
  (U)SIM application toolkit; Stage 2
  http://www.3gpp.org/DynaReport/23048.htm
- [[[3gpp-ts-23-236]]] 3GPP TS 23.236: Intra-domain connection of Radio Access
  Network (RAN) nodes to multiple Core Network (CN) nodes
  http://www.3gpp.org/DynaReport/23236.htm
- [[[3gpp-ts-24-007]]] 3GPP TS 24.007: Mobile radio interface signalling
  layer 3; General Aspects
  http://www.3gpp.org/DynaReport/24007.htm
- [[[3gpp-ts-24-008]]] 3GPP TS 24.008: Mobile radio interface Layer 3
  specification; Core network protocols; Stage 3.
  http://www.3gpp.org/dynareport/24008.htm
- [[[3gpp-ts-31-101]]] 3GPP TS 31.101: UICC-terminal interface;
  Physical and logical characteristics
  http://www.3gpp.org/DynaReport/31101.htm
- [[[3gpp-ts-31-102]]] 3GPP TS 31.102: Characteristics of the
  Universal Subscriber Identity Module (USIM) application
  http://www.3gpp.org/DynaReport/31102.htm
- [[[3gpp-ts-31-103]]] 3GPP TS 31.103: Characteristics of the
  IMS Subscriber Identity Module (ISIM) application
  http://www.3gpp.org/DynaReport/31103.htm
- [[[3gpp-ts-31-111]]] 3GPP TS 31.111: Universal Subscriber Identity
  Module (USIM) Application Toolkit (USAT)
  http://www.3gpp.org/DynaReport/31111.htm
- [[[3gpp-ts-31-115]]] 3GPP TS 31.115: Secured packet structure for
  (Universal) Subscriber Identity Module (U)SIM Toolkit applications
  http://www.3gpp.org/DynaReport/31115.htm
- [[[3gpp-ts-31-116]]] 3GPP TS 31.116: Remote APDU Structure for
  (U)SIM Toolkit applications http://www.3gpp.org/DynaReport/31116.htm
- [[[3gpp-ts-35-205]]] 3GPP TS 35.205: 3G Security; Specification of
  the MILENAGE algorithm set: General
- [[[3gpp-ts-35-206]]] 3GPP TS 35.206: 3G Security; Specification of
  the MILENAGE algorithm set: Algorithm specification
  http://www.3gpp.org/DynaReport/35206.htm
- [[[3gpp-ts-44-006]]] 3GPP TS 44.006: Mobile Station - Base Station
  System (MS - BSS) interface; Data Link (DL) layer specification
  http://www.3gpp.org/DynaReport/44006.htm
- [[[3gpp-ts-44-018]]] 3GPP TS 44.018: Mobile radio interface layer 3
  specification; Radio Resource Control (RRC) protocol
  http://www.3gpp.org/DynaReport/44018.htm
- [[[3gpp-ts-44-064]]] 3GPP TS 44.064: Mobile Station - Serving GPRS
  Support Node (MS-SGSN); Logical Link Control (LLC) Layer Specification
  http://www.3gpp.org/DynaReport/44064.htm
- [[[3gpp-ts-48-008]]] 3GPP TS 48.008: Mobile Switching Centre - Base
  Station system (MSC-BSS) interface; Layer 3 specification
  http://www.3gpp.org/DynaReport/48008.htm
- [[[3gpp-ts-48-016]]] 3GPP TS 48.016: General Packet Radio Service
  (GPRS); Base Station System (BSS) - Serving GPRS Support Node (SGSN)
  interface; Network service
  http://www.3gpp.org/DynaReport/48016.htm
- [[[3gpp-ts-48-018]]] 3GPP TS 48.018: General Packet Radio Service
  (GPRS); Base Station System (BSS) - Serving GPRS Support Node (SGSN);
  BSS GPRS protocol (BSSGP)
  http://www.3gpp.org/DynaReport/48018.htm
- [[[3gpp-ts-48-056]]] 3GPP TS 48.056: Base Station Controller - Base
  Transceiver Station (BSC - BTS) interface; Layer 2 specification
  http://www.3gpp.org/DynaReport/48056.htm
- [[[3gpp-ts-48-058]]] 3GPP TS 48.058: Base Station Controller - Base
  Transceiver Station (BSC - BTS) Interface; Layer 3 specification
  http://www.3gpp.org/DynaReport/48058.htm
- [[[3gpp-ts-51-011]]] 3GPP TS 51.011: Specification of the Subscriber
  Identity Module - Mobile Equipment (SIM-ME) interface
- [[[3gpp-ts-51-014]]] 3GPP TS 51.014: Specification of the SIM
  Application Toolkit for the Subscriber Identity Module - Mobile
  Equipment (SIM - ME) interface http://www.3gpp.org/DynaReport/51014.htm
- [[[3gpp-ts-52-021]]] 3GPP TS 52.021: Network Management (NM)
  procedures and messages on the A-bis interface
  http://www.3gpp.org/DynaReport/52021.htm

- [[[etsi-tr102216]]] ETSI TR 102 216: Smart cards
  http://www.etsi.org/deliver/etsi_tr/102200_102299/102216/03.00.00_60/tr_102216v030000p.pdf

- [[[etsi-ts102221]]] ETSI TS 102 221: Smart Cards; UICC-Terminal
  interface; Physical and logical characteristics
  http://www.etsi.org/deliver/etsi_ts/102200_102299/102221/13.01.00_60/ts_102221v130100p.pdf
- [[[etsi-ts101220]]] ETSI TS 101 220: Smart Cards; ETSI numbering
  system for telecommunication application providers
  http://www.etsi.org/deliver/etsi_ts/101200_101299/101220/12.00.00_60/ts_101220v120000p.pdf

- [[[ietf-rfc768]]] IETF RFC 768: Internet Protocol
  https://tools.ietf.org/html/rfc791
- [[[ietf-rfc793]]] IETF RFC 793: Transmission Control Protocol
  https://tools.ietf.org/html/rfc793
- [[[ietf-rfc1035]]] IETF RFC 1035: Domain Names - Implementation and Specification
  https://tools.ietf.org/html/rfc1035
- [[[ietf-rfc1350]]] IETF RFC 1350: Trivial File Transfer Protool
  https://tools.ietf.org/html/rfc1350
- [[[ietf-rfc2131]]] IETF RFC 2131: Dynamic Host Configuration Protocol
  https://tools.ietf.org/html/rfc2131
- [[[ietf-rfc2719]]] IETF RFC 2719: Signal Transport over IP
  https://tools.ietf.org/html/rfc2719
- [[[ietf-rfc3331]]] IETF RFC 3331: Message Transfer Part 2 User Adaptation Layer
  https://tools.ietf.org/html/rfc3331
- [[[ietf-rfc3550]]] IETF RFC 3550: RTP: A Transport protocol for Real-Time Applications
  https://tools.ietf.org/html/rfc3550
- [[[ietf-rfc3596]]] IETF RFC 3596: DNS Extensions to Support IP Version 6
  https://tools.ietf.org/html/rfc3596
- [[[ietf-rfc3868]]] IETF RFC 3868: SCCP User Adaptation Layer
  https://tools.ietf.org/html/rfc3868
- [[[ietf-rfc4165]]] IETF RFC 4165: Message Transfer Part 2 Peer-to-Peeer Adaptation Layer
  https://tools.ietf.org/html/rfc4165
- [[[ietf-rfc4251]]] IETF RFC 4251: The Secure Shell (SSH) Protocol Architecture
  https://tools.ietf.org/html/rfc4251
- [[[ietf-rfc4666]]] IETF RFC 4666: Message Transfer Part 3 User Adaptation Layer
  https://tools.ietf.org/html/rfc4666
- [[[ietf-rfc5771]]] IETF RFC 5771: IANA Guidelines for IPv4 Multicast Address Assignments
  https://tools.ietf.org/html/rfc5771

- [[[itu-t-q701]]] ITU-T Q.701: Functional Description of the Message Transfer Part (MTP)
  https://www.itu.int/rec/T-REC-Q.701/en/
- [[[itu-t-q711]]] ITU-T Q.711: Functional Description of the Signalling Connection Control Part
  https://www.itu.int/rec/T-REC-Q.711/en/
- [[[itu-t-q713]]] ITU-T Q.713: Signalling connection control part formats and codes
  https://www.itu.int/rec/T-REC-Q.713/en/
- [[[itu-t-q714]]] ITU-T Q.714: Signalling connection control part procedures
  https://www.itu.int/rec/T-REC-Q.714/en/
- [[[itu-t-q921]]] ITU-T Q.921: ISDN user-network interface -
  Data link layer specification
  https://www.itu.int/rec/T-REC-Q.921/en

- [[[smpp-34]]] SMPP Develoepers Forum. Short Message Peer-to-Peer
  Protocol Specification v3.4
  http://docs.nimta.com/SMPP_v3_4_Issue1_2.pdf

- [[[gnu-agplv3]]] Free Software Foundation.  GNU Affero General Public
  License.  http://www.gnu.org/licenses/agpl-3.0.en.html
- [[[freeswitch_pbx]]] FreeSWITCH SIP PBX
  https://freeswitch.org
