[[bts]]
== Reviewing and Provisioning BTS configuration

The main functionality of the BSC component is to manage BTSs.  As such,
provisioning BTSs within the BSC is one of the most common tasks during
BSC operation.   Just like about anything else in OpenBSC, they are
configured using the VTY.

BTSs are internally numbered with integer numbers starting from "0" for
the first BTS.  BTS numbers have to be contiguous, so you cannot
configure 0,1,2 and then 5.


=== Reviewing current BTS status and configuration

In order to view the status and properties of a BTS, you can issue the
`show bts` command.  If used without any BTS number, it will display
information about all provisioned BTS numbers.

----
OpenBSC> show bts 0
BTS 0 is of nanobts type in band DCS1800, has CI 0 LAC 1, BSIC 63, TSC 7 and 1 TRX
Description: (null)
MS Max power: 15 dBm
Minimum Rx Level for Access: -110 dBm
Cell Reselection Hysteresis: 4 dBm
RACH TX-Integer: 9
RACH Max transmissions: 7
System Information present: 0x0000007e, static: 0x00000000
  Unit ID: 200/0/0, OML Stream ID 0xff
  NM State: Oper 'Enabled', Admin 2, Avail 'OK'
  Site Mgr NM State: Oper 'Enabled', Admin 0, Avail 'OK'
  Paging: 0 pending requests, 0 free slots
  OML Link state: connected.
  Current Channel Load:
                   TCH/F:   0% (0/5)
                  SDCCH8:   0% (0/8)
----

You can also review the status of the TRXs configured within the BTSs of
this BSC by using `show trx`:

----
OpenBSC> show trx 0 0
TRX 0 of BTS 0 is on ARFCN 871
Description: (null)
  RF Nominal Power: 23 dBm, reduced by 0 dB, resulting BS power: 23 dBm
  NM State: Oper 'Enabled', Admin 2, Avail 'OK'
  Baseband Transceiver NM State: Oper 'Enabled', Admin 2, Avail 'OK'
  ip.access stream ID: 0x00
----

The output can be restricted to the TRXs of one specified BTS number
(`show trx 0`) or even that of a single specified TRX within a
specified BTS (`show trx 0 0`).

Furthermore, information on the individual timeslots can be shown by
means of `show timeslot`.  The output can be restricted to the
timeslots of a single BTS (`show timeslot 0`) or that of a single
TRX (`show timeslot 0 0`).  Finally, you can restrict the output to
a single timeslot by specifying the BTS, TRX and TS numbers (`show
timeslot 0 0 4`).

----
OpenBSC> show timeslot 0 0 0
BTS 0, TRX 0, Timeslot 0, phys cfg CCCH, TSC 7
  NM State: Oper 'Enabled', Admin 2, Avail 'OK'
OpenBSC> show timeslot 0 0 1
BTS 0, TRX 0, Timeslot 1, phys cfg SDCCH8, TSC 7
  NM State: Oper 'Enabled', Admin 2, Avail 'OK'
----


=== Provisioning a new BTS

In order to provision BTSs, you have to enter the BTS config node of the
VTY.  In order to configure BTS 0, you can issue the following sequence
of commands:
----
OpenBSC> enable
OpenBSC# configure terminal
OpenBSC(config)# network
OpenBSC(config-net)# bts 0
OpenBSC(config-net-bts)#
----

At this point, you have a plethora of commands, in fact an entire
hierarchy of commands to configure all aspects of the BTS, as well as
each of its TRX and each timeslot within each TRX.  For a full
reference, please consult the respective chapter in the VTY reference of
OpenBSC.

BTS configuration depends quite a bit on the specific BTS vendor and
model.  The section below provides just one possible example for the
case of a sysmoBTS.


----
OpenBSC(config-net-bts)# type sysmobts
OpenBSC(config-net-bts)# band DCS1800
OpenBSC(config-net-bts)# description The new BTS in Baikonur
OpenBSC(config-net-bts)# location_area_code 2342
OpenBSC(config-net-bts)# cell_identity 5
OpenBSC(config-net-bts)# base_station_id_code 63
OpenBSC(config-net-bts)# ip.access unit_id 8888 0
OpenBSC(config-net-bts)# ms max power 40
OpenBSC(config-net-bts)# trx 0
OpenBSC(config-net-bts-trx)# arfcn 871
OpenBSC(config-net-bts-trx)# nominal power 23
OpenBSC(config-net-bts-trx)# max_power_red 0
OpenBSC(config-net-bts-trx)# timeslot 0
OpenBSC(config-net-bts-trx-ts)# phys_chan_config CCCH+SDCCH4
OpenBSC(config-net-bts-trx-ts)# exit
OpenBSC(config-net-bts-trx)# timeslot 1
OpenBSC(config-net-bts-trx-ts)# phys_chan_config TCH/F
OpenBSC(config-net-bts-trx-ts)# exit
OpenBSC(config-net-bts-trx)# timeslot 2
OpenBSC(config-net-bts-trx-ts)# phys_chan_config TCH/F
OpenBSC(config-net-bts-trx-ts)# exit
OpenBSC(config-net-bts-trx)# timeslot 3
OpenBSC(config-net-bts-trx-ts)# phys_chan_config TCH/F
OpenBSC(config-net-bts-trx-ts)# exit
OpenBSC(config-net-bts-trx)# timeslot 4
OpenBSC(config-net-bts-trx-ts)# phys_chan_config TCH/F
OpenBSC(config-net-bts-trx-ts)# exit
OpenBSC(config-net-bts-trx)# timeslot 5
OpenBSC(config-net-bts-trx-ts)# phys_chan_config TCH/F
OpenBSC(config-net-bts-trx-ts)# exit
OpenBSC(config-net-bts-trx)# timeslot 6
OpenBSC(config-net-bts-trx-ts)# phys_chan_config TCH/F
OpenBSC(config-net-bts-trx-ts)# exit
OpenBSC(config-net-bts-trx)# timeslot 7
OpenBSC(config-net-bts-trx-ts)# phys_chan_config PDCH
OpenBSC(config-net-bts-trx-ts)# exit
----


=== System Information configuration

A GSM BTS periodically transmits a series of 'SYSTEM INFORMATION'
messages to mobile stations, both via the BCCH in idle mode, was well as
via the SACCH in dedicated mode.  There are many different types of such
messages. For their detailed contents and encoding, please see _3GPP TS
24.008_ <<3gpp-ts-24-008>>.

For each of the 'SYSTEM INFORMATION' message types, you can configure to
have the BSC generate it automatically ('computed'), or you can specify
the respective binary message as a string of hexadecimal digits.

The default configuration is to compute all (required) 'SYSTEM
INFORMATION' messages automatically.

Please see the _OsmoBSC VTY Reference Manual_ <<vty-ref-osmobsc>> for
further information, particularly on the following commands:

* `system-information (1|2|3|4|5|6|7|8|9|10|13|16|17|18|19|20|2bis|2ter|2quater|5bis|5ter) mode (static|computed)`
* `system-information (1|2|3|4|5|6|7|8|9|10|13|16|17|18|19|20|2bis|2ter|2quater|5bis|5ter) static HEXSTRING`


=== Neighbor List configuration

Every BTS sends a list of ARFCNs of neighbor cells
. within its 'SYSTEM INFORMATION 2' (and 2bis/2ter)  messages on the BCCH
. within its 'SYSTEM INFORMATION 5' messages on SACCH in dedicated mode

For every BTS config node in the VTY, you can specify the behavior of
the neighbor list using the `neighbor list mode` VTY command:

automatic::
	Automatically generate a list of neighbor cells using all other
	BTSs configured in the VTY
manual::
	Manually specify the neighbor list by means of `neighbor-list
(add|del) arfcn <0-1023>` commands, having identical neighbor lists on
BCCH (SI2) and SACCH (SI5)

manual-si5::
	Manually specify the neighbor list by means of `neighbor-list
(add|del) arfcn <0-1023>` for BCCH (SI2) and a separate neighbor list by
means of `si5 neighbor-list (add|del) arfcn <0-1023>` for SACCH (SI5).


=== Configuring GPRS PCU parameters of a BTS

In the case of BTS models using Abis/IP (IPA), the GPRS PCU is located
inside the BTS.  The BTS then establishes a Gb connection to the SGSN.

All the BTS-internal PCU configuration is performed via A-bis OML by
means of configuring the 'CELL', 'NSVC' (NS Virtual Connection and 'NSE'
(NS Entity).

There is one 'CELL' node and one 'NSE' node, but there are two 'NSVC'
nodes.  At the time of this writing, only the NSVC 0 is supported by
OsmoBTS, while both NSVC are supported by the ip.access nanoBTS.

The respective VTY configuration parameters are described below.  They
all exist beneath each BTS VTY config node.

But let's first start with a small example

.Example configuration of GPRS PCU parameters at VTY BTS node
----
OpenBSC(config-net-bts)# gprs mode gprs
OpenBSC(config-net-bts)# gprs routing area 1
OpenBSC(config-net-bts)# gprs cell bvci 1234
OpenBSC(config-net-bts)# gprs nsei 1234
OpenBSC(config-net-bts)# gprs nsvc 0 nsvci 1234
OpenBSC(config-net-bts)# gprs nsvc 0 local udp port 23000
OpenBSC(config-net-bts)# gprs nsvc 0 remote udp port 23000
OpenBSC(config-net-bts)# gprs nsvc 0 remote ip 192.168.100.239
----


=== More explanation about the PCU config parameters

//FIXME: should this go into VTY additions?

==== `gprs mode (none|gprs|egprs)`

This command determines if GPRS (or EGPRS) services are to be enabled in
this cell at all.


==== `gprs cell bvci <2-65535>`

Configures the 'BSSGP Virtual Circuit Identifier'.  It must be unique
between all BGSGP connections to one SGSN.

NOTE: It is up to the system administrator to ensure all PCUs are
allocated an unique bvci.  OsmoBSC will not ensure this policy.


==== `gprs nsei <0-65535>`

Configures the 'NS Entity Identifier'.  It must be unique between all NS
connections to one SGSN.

NOTE: It is up to the system administrator to ensure all PCUs are
allocated an unique bvci.  OsmoBSC will not ensure this policy.


==== `gprs nsvc <0-1> nsvci <0-65535>`

Configures the 'NS Virtual Connection Identifier'.  It must be unique
between all NS virtual connections to one SGSN.

NOTE: It is up to the system administrator to ensure all PCUs are
allocated an unique nsvci.  OsmoBSC will not ensure this policy.


==== `gprs nsvc <0-1> local udp port <0-65535>`

Configures the local (PCU side) UDP port for the NS-over-UDP link.


==== `gprs nsvc <0-1> remote udp port <0-65535>`

Configures the remote (SGSN side) UDP port for the NS-over-UDP link.


==== `gprs nsvc <0-1> remote ip A.B.C.D`

Configures the remote (SGSN side) UDP port for the NS-over-UDP link.


==== `gprs ns timer (tns-block|tns-block-retries|tns-reset|tns-reset-retries|tns-test|tns-alive|tns-alive-retries)` <0-255>

Configures the various GPRS NS related timers.  Please check the GPRS NS
specification for the detailed meaning of those timers.
