[glossary]
== Glossary

2FF::
  2nd Generation Form Factor; the so-called plug-in SIM form factor
3FF::
  3rd Generation Form Factor; the so-called microSIM form factor
3GPP::
  3rd Generation Partnership Project
4FF::
  4th Generation Form Factor; the so-called nanoSIM form factor
A Interface::
  Interface between BTS and BSC, traditionally over E1 (_3GPP TS 48.008_
  <<3gpp-ts-48-008>>)
A3/A8::
  Algorithm 3 and 8; Authentication and key generation algorithm in GSM
  and GPRS, typically COMP128v1/v2/v3 or MILENAGE are typically used
A5::
  Algorithm 5; Air-interface encryption of GSM; currently only A5/0
  (no encryption), A5/1 and A5/3 are in use
Abis Interface::
  Interface between BTS and BSC, traditionally over E1 (_3GPP TS 48.058_
  <<3gpp-ts-48-058>> and _3GPP TS 52.021_ <<3gpp-ts-52-021>>)
ACC::
  Access Control Class; every BTS broadcasts a bit-mask of permitted
  ACC, and only subscribers with a SIM of matching ACC are permitted
  to use that BTS
AGCH::
  Access Grant Channel on Um interface; used to assign a dedicated
  channel in response to RACH request
AGPL::
  GNU Affero General Public License, a copyleft-style Free Software License
ARFCN::
  Absolute Radio Frequency Channel Number; specifies a tuple of uplink
  and downlink frequencies
AUC::
  Authentication Center; central database of authentication key material
  for each subscriber
BCCH::
  Broadcast Control Channel on Um interface; used to broadcast
  information about Cell and its neighbors
BCC::
  Base Station Color Code; short identifier of BTS, lower part of BSIC
BTS::
  Base Transceiver Station
BSC::
  Base Station Controller
BSIC::
  Base Station Identity Code; 16bit identifier of BTS within location area
BSSGP::
  Base Station Subsystem Gateway Protocol (_3GPP TS 48.018_ <<3gpp-ts-48-018>>)
BVCI::
  BSSGP Virtual Circuit Identifier
CBCH::
  Cell Broadcast Channel; used to transmit Cell Broadcast SMS (SMS-CB)
CC::
  Call Control; Part of the GSM Layer 3 Protocol
CCCH::
  Common Control Channel on Um interface; consists of RACH (uplink),
  BCCH, PCH, AGCH (all downlink)
Cell::
  A cell in a cellular network, served by a BTS
CEPT::
  Conférence européenne des administrations des postes et des
  télécommunications; European Conference of Postal and Telecommunications
  Administrations.
CGI::
  Cell Global Identifier comprised of MCC, MNC, LAC and BSIC
CSFB::
  Circiut-Switched Fall Back; Mechanism for switching from LTE/EUTRAN to UTRAN/GERAN when circuit-switched
  services such as voice telephony are required.
dB::
  deci-Bel; relative logarithmic unit
dBm::
  deci-Bel (milliwatt); unit of measurement for signal strength of radio
  signals
DHCP::
  Dynamic Host Configuration Protocol (_IETF RFC 2131_ <<ietf-rfc2131>>
downlink::
  Direction of messages / signals from the network core towards the
  mobile phone
DSP::
  Digital Signal Processor
dvnixload::
  Tool to program UBL and the Bootloader on a sysmoBTS
EDGE::
  Enhanced Data rates for GPRS Evolution; Higher-speed improvement of
  GPRS; introduces 8PSK
EGPRS::
  Enhanced GPRS; the part of EDGE relating to GPRS services
EIR::
  Equipment Identity Register; core network element that stores and manages
  IMEI numbers
ESME::
  External SMS Entity; an external application interfacing with a SMSC
  over SMPP
ETSI::
  European Telecommunications Standardization Institute
FPGA::
  Field Programmable Gate Array; programmable digital logic hardware
Gb::
  Interface between PCU and SGSN in GPRS/EDGE network; uses NS, BSSGP, LLC
GERAN::
  GPRS/EDGE Radio Access Network
ifdef::gfdl-enabled[]
GFDL::
  GNU Free Documentation License; a copyleft-style Documentation License
endif::[]
GGSN::
  GPRS Gateway Support Node; gateway between GPRS and external (IP) network
GMSK::
  Gaussian Minimum Shift Keying; modulation used for GSM and GPRS
GPL::
  GNU General Public License, a copyleft-style Free Software License
Gp::
  Gp interface between SGSN and GGSN; uses GTP protocol
GPRS::
  General Packet Radio Service; the packet switched 2G technology
GPS::
  Global Positioning System; provides a highly accurate clock reference
  besides the global position
GSM::
  Global System for Mobile Communications.  ETSI/3GPP Standard of a 2G
  digital cellular network
GSMTAP::
  GSM tap; pseudo standard for encapsulating GSM protocol layers over
  UDP/IP for analysis
GSUP::
  Generic ubscriber Update Protocol.  Osmocom-specific alternative to TCAP/MAP
GT::
  Global Title; an address in SCCP
GTP::
  GPRS Tunnel Protocol; used between SGSN and GGSN
HLR::
  Home Location Register; central subscriber database of a GSM network
HNB-GW::
  Home NodeB Gateway.  Entity between femtocells (Home NodeB) and CN in 3G/UMTS.
HPLMN::
  Home PLMN; the network that has issued the subscriber SIM and has his record in HLR
IE::
  Information Element
IMEI::
  International Mobile Equipment Identity; unique 14-digit decimal number to
  globally identify a mobile device, optionally with a 15th checksum digit
IMEISV::
  IMEI software version; unique 14-digit decimal number to globally identify a
  mobile device (same as IMEI) plus two software version digits (total digits: 16)
IMSI::
  International Mobile Subscriber Identity; 15-digit unique identifier
  for the subscriber/SIM; starts with MCC/MNC of issuing operator
IP::
  Internet Protocol (_IETF RFC 791_ <<ietf-rfc791>>)
IPA::
  _ip.access GSM over IP_ protocol; used to multiplex a single TCP connection
Iu::
  Interface in 3G/UMTS between RAN and CN
IuCS::
  Iu interface for circuit-switched domain.  Used in 3G/UMTS between RAN and MSC
IuPS::
  Iu interface for packet-switched domain.  Used in 3G/UMTS between RAN and SGSN
LAC::
  Location Area Code; 16bit identifier of Location Area within network
LAPD::
  Link Access Protocol, D-Channel (_ITU-T Q.921_ <<itu-t-q921>>)
LAPDm::
  Link Access Protocol Mobile (_3GPP TS 44.006_ <<3gpp-ts-44-006>>)
LLC::
  Logical Link Control; GPRS protocol between MS and SGSN (_3GPP TS
  44.064_ <<3gpp-ts-44-064>>)
Location Area::
  Location Area; a geographic area containing multiple BTS
LU::
  Location Updating; can be of type IMSI-Attach or Periodic. Procedure that
  indicates a subscriber's physical presence in a given radio cell.
M2PA::
  MTP2 Peer-to-Peer Adaptation; a SIGTRAN Variant (_RFC 4165_ <<ietf-rfc4165>>)
M2UA::
  MTP2 User Adaptation; a SIGTRAN Variant (_RFC 3331_ <<ietf-rfc3331>>)
M3UA::
  MTP3 User Adaptation; a SIGTRAN Variant (_RFC 4666_ <<ietf-rfc4666>>)
MCC::
  Mobile Country Code; unique identifier of a country, e.g. 262 for Germany
MFF::
  Machine-to-Machine Form Factor; a SIM chip package that is soldered
  permanently onto M2M device circuit boards.
MGW::
  Media Gateway
MM::
  Mobility Management; part of the GSM Layer 3 Protocol
MNC::
  Mobile Network Code; identifies network within a country; assigned by national regulator
MNCC::
  Mobile Network Call Control; Unix domain socket based Interface between MSC and external call control entity
  like osmo-sip-connector
MNO::
  Mobile Network Operator; operator with physical radio network under his MCC/MNC
MO::
  Mobile Originated.  Direction from Mobile (MS/UE) to Network
MS::
  Mobile Station; a mobile phone / GSM Modem
MSC::
  Mobile Switching Center; network element in the circuit-switched
  core network
MSC pool::
  A number of redundant MSCs serving the same core network, which a BSC / RNC
  distributes load across; see also the "MSC Pooling" chapter in OsmoBSC's user
  manual <<userman-osmobsc>> and _3GPP TS 23.236_ <<3gpp-ts-23-236>>
MSISDN::
  Mobile Subscriber ISDN Number; telephone number of the subscriber
MT::
  Mobile Terminated.  Direction from Network  to Mobile (MS/UE)
MTP::
  Message Transfer Part; SS7 signaling protocol (_ITU-T Q.701_ <<itu-t-q701>>)
MVNO::
  Mobile Virtual Network Operator; Operator without physical radio network
NCC::
  Network Color Code; assigned by national regulator
NITB::
  Network In The Box; combines functionality traditionally provided
  by BSC, MSC, VLR, HLR, SMSC functions; see OsmoNITB
NRI::
  Network Resource Indicator, typically 10 bits of a TMSI indicating which MSC
  of an MSC pool attached the subscriber; see also the "MSC Pooling" chapter in
  OsmoBSC's user manual <<userman-osmobsc>> and _3GPP TS 23.236_ <<3gpp-ts-23-236>>
NSEI::
  NS Entity Identifier
NVCI::
  NS Virtual Circuit Identifier
NWL::
  Network Listen; ability of some BTS to receive downlink from other BTSs
NS::
  Network Service; protocol on Gb interface (_3GPP TS 48.016_ <<3gpp-ts-48-016>>)
OCXO::
  Oven Controlled Crystal Oscillator; very high precision oscillator,
  superior to a VCTCXO
OML::
  Operation & Maintenance Link (ETSI/_3GPP TS 52.021_ <<3gpp-ts-52-021>>)
OpenBSC::
  Open Source implementation of GSM network elements, specifically OsmoBSC, OsmoNITB, OsmoSGSN
OpenGGSN::
  Open Source implementation of a GPRS Packet Control Unit
OpenVPN::
  Open-Source Virtual Private Network;  software employed to establish
  encrypted private networks over untrusted public networks
Osmocom::
  Open Source MObile COMmunications; collaborative community for
  implementing communications protocols and systems, including GSM, GPRS,
  TETRA, DECT, GMR and others
OsmoBSC::
  Open Source implementation of a GSM Base Station Controller
OsmoNITB::
  Open Source implementation of a GSM Network In The Box, combines
  functionality traditionally provided by  BSC, MSC, VLR, HLR, AUC, SMSC
OsmoSGSN::
  Open Source implementation of a Serving GPRS Support Node
OsmoPCU::
  Open Source implementation of a GPRS Packet Control Unit
OTA::
  Over-The-Air; Capability of operators to remotely
  reconfigure/reprogram ISM/USIM cards
PC::
  Point Code; an address in MTP
PCH::
  Paging Channel on downlink Um interface; used by network to page an MS
PCU::
  Packet Control Unit; used to manage Layer 2 of the GPRS radio interface
PDCH::
  Packet Data Channel on Um interface; used for GPRS/EDGE signalling + user data
PIN::
  Personal Identification Number; a number by which the user
  authenticates to a SIM/USIM or other smart card
PLMN::
  Public Land Mobile Network; specification language for a single GSM network
PUK::
  PIN Unblocking Code; used to unblock a blocked PIN (after too many
  wrong PIN attempts)
RAC::
  Routing Area Code; 16bit identifier for a Routing Area within a Location Area
RACH::
  Random Access Channel on uplink Um interface; used by MS to request
  establishment of a dedicated channel
RAM::
  Remote Application Management; Ability to remotely manage
  (install, remove) Java Applications on SIM/USIM Card
RF::
  Radio Frequency
RFM::
  Remote File Management; Ability to remotely manage (write, read)
  files on a SIM/USIM card
Roaming::
  Procedure in which a subscriber of one network is using the radio
  network of another network, often in different countries; in some
  countries national roaming exists
Routing Area::
  Routing Area; GPRS specific sub-division of Location Area
RR::
  Radio Resources; Part of the GSM Layer 3 Protocol
RSL::
  Radio Signalling Link (_3GPP TS 48.058_ <<3gpp-ts-48-058>>)
RTP::
  Real-Time Transport Protocol (_IETF RFC 3550_ <<ietf-rfc3550>>); Used to
  transport audio/video streams over UDP/IP
SACCH::
  Slow Associate Control Channel on Um interface; bundled to a TCH or
  SDCCH, used for signalling in parallel to active dedicated channel
SCCP::
  Signaling Connection Control Part; SS7 signaling protocol (_ITU-T Q.711_ <<itu-t-q711>>)
SDCCH::
  Slow Dedicated Control Channel on Um interface; used for signalling
  and SMS transport in GSM
SDK::
  Software Development Kit
SGs::
  Interface between MSC (GSM/UMTS) and MME (LTE/EPC) to facilitate CSFB and SMS.
SGSN::
  Serving GPRS Support Node; Core network element for packet-switched services in GSM and UMTS.
SIGTRAN::
  Signaling Transport over IP (_IETF RFC 2719_ <<ietf-rfc2719>>)
SIM::
  Subscriber Identity Module; small chip card storing subscriber identity
Site::
  A site is a location where one or more BTSs are installed,
  typically three BTSs for three sectors
SMPP::
  Short Message Peer-to-Peer; TCP based protocol to interface external
  entities with an SMSC
SMSC::
  Short Message Service Center; store-and-forward relay for short messages
SS7::
  Signaling System No. 7; Classic digital telephony signaling system
SS::
  Supplementary Services; query and set various service parameters between
  subscriber and core network (e.g. USSD, 3rd-party calls, hold/retrieve,
  advice-of-charge, call deflection)
SSH::
  Secure Shell; _IETF RFC 4250_ <<ietf-rfc4251>> to 4254
SSN::
  Sub-System Number; identifies a given SCCP Service such as MSC, HLR
STP::
  Signaling Transfer Point; A Router in SS7 Networks
SUA::
  SCCP User Adaptation; a SIGTRAN Variant (_RFC 3868_ <<ietf-rfc3868>>)
syslog::
  System logging service of UNIX-like operating systems
System Information::
  A set of downlink messages on the BCCH and SACCH of the Um interface
  describing properties of the cell and network
TCH::
  Traffic Channel; used for circuit-switched user traffic (mostly voice)
  in GSM
TCP::
  Transmission Control Protocol; (_IETF RFC 793_ <<ietf-rfc793>>)
TFTP::
  Trivial File Transfer Protocol; (_IETF RFC 1350_ <<ietf-rfc1350>>)
TRX::
  Transceiver; element of a BTS serving a single carrier
TS::
  Technical Specification
u-Boot::
  Boot loader used in various embedded systems
UBI::
  An MTD wear leveling system to deal with NAND flash in Linux
UBL::
  Initial bootloader loaded by the TI Davinci SoC
UDP::
  User Datagram Protocol (_IETF RFC 768_ <<ietf-rfc768>>)
UICC::
  Universal Integrated Chip Card;  A smart card according to _ETSI
  TR 102 216_ <<etsi-tr102216>>
Um interface::
  U mobile; Radio interface between MS and BTS
uplink::
  Direction of messages: Signals from the mobile phone towards the network
USIM::
  Universal Subscriber Identity Module; application running on a UICC
  to provide subscriber identity for UMTS and GSM networks
USSD::
  Unstructured Supplementary Service Data; textual dialog between subscriber
  and core network, e.g. '*#100#' -> 'Your extension is 1234'
VCTCXO::
  Voltage Controlled, Temperature Compensated Crystal Oscillator;  a
  precision oscillator, superior to a classic crystal oscillator, but
  inferior to an OCXO
VLR::
  Visitor Location Register; volatile storage of attached subscribers in
  the MSC
VPLMN::
  Visited PLMN; the network in which the subscriber is currently
  registered; may differ from HPLMN when on roaming
VTY::
  Virtual TeletYpe; a textual command-line interface for configuration
  and introspection, e.g. the OsmoBSC configuration file as well as
  its telnet link on port 4242

